export { default as cirugiaDog } from "./cirugiaDog.png";
export { default as cirugiaDogTwo } from "./cirugiaDogTwo.png";
export { default as esteticaDog } from "./esteticaDog.png";
export { default as guarderiaDog } from "./guarderiaDog.png";
export { default as limpiezasDog } from "./limpiezasDog.png";
export { default as supportDog } from "./supportDog.png";
export { default as vacunacionDog } from "./vacunacionDog.png";
export { default as shivaDog } from "./shivaDog.png"
export { default as grassDog } from "./grassDog.png"
export { default as ucomingDog } from "./ucomingDog.png"
export { default as whatDog } from "./whatDog.png"
export { default as grayLookingDog } from "./grayLookingDog.png"
export { default as graynotGrayDog } from "./graynotGrayDog.png"